# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Nuxt app

permissions:
  contents: read
  pages: write
  id-token: write
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run generate
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: blog-app
        path: .output/public

  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: production

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: blog-app
    - name: Deploy to Github pages
      uses: actions/deploy-pages@v1-beta
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
